name: CI/CD Pipeline with Spring Boot, Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      # Dar permisos de ejecución al wrapper de Gradle
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x gradlew
      # Construir el proyecto
      - name: Build with Gradle
        run: ./gradlew clean build

      # Verificar el archivo JAR generado
      - name: Verify JAR file
        run: ls build/libs/
      # Iniciar el servidor Spring Boot para pruebas locales
      - name: Start Spring Boot Server
        run: |
          nohup java -jar build/libs/*.jar & # Usar el JAR generado
        env:
          SPRING_PROFILES_ACTIVE: test
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t gjimenez07/cicd-pipeline .
      - name: Publish image to docker hub
        run: docker push gjimenez07/cicd-pipeline:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Pull Image from docker hub
      run: docker pull gjimenez07/cicd-pipeline:latest
    - name: Delete old container
      run: docker rm -f cicd-pipeline-container
    - name: Run docker container
      run: docker run -d -p 8080:8080 --name cicd-pipeline-container gjimenez07/cicd-pipeline